project_id = "jqxjerhqddifcrrskaaq"

[functions.polymarket-proxy-markets]
verify_jwt = false

[functions.polymarket-proxy-orderbook]
verify_jwt = false

[functions.polymarket-proxy-trades]
verify_jwt = false

[functions.polymarket-proxy-events]
verify_jwt = false

[functions.polymarket-proxy-history]
verify_jwt = false

[functions.polymarket-positions]
verify_jwt = false

[functions.polymarket-health]
verify_jwt = false

[functions.polymarket-has-creds]
verify_jwt = false

[functions.polymarket-test-auth]
verify_jwt = false

[functions.polymarket-l1-derive-creds]
verify_jwt = false

[functions.polymarket-post-signed-order]
verify_jwt = false

[functions.polymarket-cancel-order]
verify_jwt = false

[functions.polymarket-create-deposit-address]
verify_jwt = false

[functions.polymarket-user-creds-status]
verify_jwt = false

[functions.polymarket-withdraw]
verify_jwt = false

[functions.polymarket-orders]
verify_jwt = false

[functions.polymarket-deposit-status]
verify_jwt = false
